### ISSUE TITLE
Runs, renders, but "nothing to commit"

### ISSUE THREAD

**Issue by lswank** [nielsvaneck/render-md-mermaid#1]
The example on the page, even when providing a valid path runs but says "nothing to commit" in the logs on the auto-commit-action.

**Comment by nielsvaneck** [comment]
not sure what your reproduction steps are, but have you tried removing the example images or changing the graph definitions?

**Comment by danielloader** [comment]
Think I can shine some light on this @lswank 

```
$ docker run -it -v /path/to/diagrams:/data --entrypoint bash minlag/mermaid-cli
mermaidcli@64bbea1ff322:/$ find . -name mmdc
./home/mermaidcli/node_modules/.bin/mmdc
./home/mermaidcli/.cache/yarn/v6/.tmp/0be863b9afb222f53eb609791cf5e2c4/.bin/mmdc
./home/mermaidcli/.cache/yarn/v6/npm-@mermaid-js-mermaid-cli-8.11.0-bbcd91e448f003155975601a65885ed153898298/node_modules/@mermaid-js/mermaid-cli/.bin/mmdc
mermaidcli@64bbea1ff322:/$ stat /usr/local/bin/mmdc
stat: cannot stat '/usr/local/bin/mmdc': No such file or directory
```

https://github.com/mermaid-js/mermaid-cli/blob/master/Dockerfile#L15

![image](https://user-images.githubusercontent.com/933423/125792383-883f0639-9ae0-4fdb-bb0e-a5d4c6576fd5.png)

Seems to be passing as successful in the script despite it failing to find a binary inside the docker image being used, I suspect the path to a `mmdc` entrypoint changed in `minlag/mermaid-cli` at some point, and this action is using the latest tag.

EDIT: here's the change made:
https://github.com/mermaid-js/mermaid-cli/commit/8888b19f9f6256d11f5e2bc75e92615548d14cdd#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L13

Though interestingly May26th and the original issue is from Feb, but here we are.

**Comment by danielloader** [comment]
https://github.com/nielsvaneck/render-md-mermaid/pull/2 Put in a pull request to catch these issues in future, would have bailed with non zero exit code and failed the pipeline if it couldn't find `mmdc`

**Comment by nielsvaneck** [comment]
Thank you, @danielloader !

**Comment by danielloader** [comment]
Just need to change the binary location in the bash script and we should be set.

**Comment by nielsvaneck** [comment]
Done!

**Comment by danielloader** [comment]
Excited for v2 release now, thanks.
